name: Deploy static site to S3 + CloudFront

on:
  push:
    branches: [ main ]
    paths:
      - "site/**"

concurrency:
  group: deploy-static-site
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync site s3://misael-static-site-2025 --delete \
            --cache-control "public,max-age=31536000" \
            --exclude "index.html" --exclude "404.html"
          aws s3 cp site/index.html s3://misael-static-site-2025/index.html --content-type text/html --cache-control "no-cache"
          if [ -f site/404.html ]; then
            aws s3 cp site/404.html s3://misael-static-site-2025/404.html --content-type text/html --cache-control "no-cache"
          fi

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
